(()=>{const q=new URLSearchParams(location.search);if(!q.has("debug")&&!location.hostname.includes("github.io"))return;
const box=document.createElement("div");box.id="tq-screen-log";
Object.assign(box.style,{position:"fixed",left:"6px",right:"6px",bottom:"6px",maxHeight:"42vh",zIndex:"2147483647",background:"rgba(0,0,0,.86)",color:"#d7f7ff",font:"11px/1.35 monospace",border:"1px solid #46d9ff",borderRadius:"7px",whiteSpace:"pre-wrap",pointerEvents:"auto",display:"flex",flexDirection:"column",overflow:"hidden"});
const head=document.createElement("button");head.type="button";head.textContent="TQ DEBUG • abrir";head.style.cssText="display:block;width:100%;flex:0 0 auto;border:0;border-radius:6px;background:rgba(0,0,0,.96);color:#46d9ff;font:700 12px/1.2 monospace;text-align:left;padding:10px;touch-action:manipulation;position:sticky;top:0;z-index:2";
const out=document.createElement("div");out.style.cssText="display:none;overflow:auto;max-height:calc(42vh - 38px);padding:8px";
box.append(head,out);document.documentElement.appendChild(box);
let small=true;
head.onclick=()=>{small=!small;out.style.display=small?"none":"block";head.textContent=small?"TQ DEBUG • abrir":"TQ DEBUG • fechar";};
const fmt=v=>{try{return typeof v==="string"?v:JSON.stringify(v)}catch{return String(v)}};
const add=(level,...args)=>{const line=document.createElement("div");line.textContent=new Date().toLocaleTimeString()+" ["+level+"] "+args.map(fmt).join(" ");if(level==="ERROR")line.style.color="#ff8c8c";out.appendChild(line);while(out.childNodes.length>80)out.firstChild.remove();out.scrollTop=out.scrollHeight};
["log","info","warn","error"].forEach(k=>{const old=console[k].bind(console);console[k]=(...a)=>{old(...a);add(k.toUpperCase(),...a)}});
window.addEventListener("error",e=>add("ERROR",e.message,e.filename+":"+e.lineno+":"+e.colno));
window.addEventListener("unhandledrejection",e=>add("PROMISE",e.reason?.stack||e.reason||"rejection"));
add("BOOT",location.href);window.tqScreenLog=add;})();