export class AmmoEditor{
  constructor(){
    this.catalog={schema:"tq.ammo-catalog",version:1,defaultAmmoId:"cannonball-standard",ammo:[]};
    this.drafts=[];this.selectedId=null;this.storageKey="tq.dev.ammo-drafts:v1";this.el=null;
  }
  async mount(parent){
    this.el=document.createElement("section");this.el.className="tq-dev__ships tq-dev__ammo";this.el.hidden=true;
    this.el.innerHTML='<header><div><strong>Munições</strong><small>Tipos de munição naval, efeitos e valores de loja</small></div><button type="button" data-ammo-close aria-label="Fechar">×</button></header><div class="tq-ships__body"><aside class="tq-ships__sidebar"><button type="button" class="tq-ships__new" data-ammo-new>＋ Nova munição</button><div class="tq-ships__list" data-ammo-list></div></aside><main class="tq-ships__editor" data-ammo-editor></main></div>';
    parent.append(this.el);this.el.querySelector("[data-ammo-close]").onclick=()=>this.setVisible(false);this.el.querySelector("[data-ammo-new]").onclick=()=>this.create();await this.load();
  }
  async load(){try{const r=await fetch("./src/config/ammo-catalog.json?v=20261002-0908",{cache:"no-store"});if(r.ok)this.catalog=await r.json()}catch(e){console.warn("Ammo catalog load failed",e)}try{const d=JSON.parse(localStorage.getItem(this.storageKey)||"[]");this.drafts=Array.isArray(d)?d:[]}catch{this.drafts=[]}this.selectedId=this.all()[0]?.id||null;this.render()}
  all(){const m=new Map((this.catalog.ammo||[]).map(x=>[x.id,structuredClone(x)]));for(const x of this.drafts)m.set(x.id,structuredClone(x));return [...m.values()]}
  current(){return this.all().find(x=>x.id===this.selectedId)||null}
  save(v){const i=this.drafts.findIndex(x=>x.id===v.id);if(i>=0)this.drafts[i]=v;else this.drafts.push(v);localStorage.setItem(this.storageKey,JSON.stringify(this.drafts));globalThis.dispatchEvent(new CustomEvent("tq:ammoprofilechange",{detail:{ammoId:v.id}}))}
  create(){let n=1,id="ammo-"+n;while(this.all().some(x=>x.id===id))id="ammo-"+(++n);this.save({id,name:"Nova munição",available:true,damage:10,projectileSpeed:720,size:1,cooldownMs:900,effects:{projectile:"standard",impact:"standard",waterSplash:"standard"},shop:{purchasable:true,price:1}});this.selectedId=id;this.render()}
  setVisible(show){if(this.el)this.el.hidden=!show;if(show)this.render()}
  render(){if(!this.el)return;const list=this.el.querySelector("[data-ammo-list]");list.innerHTML=this.all().map(x=>'<button type="button" class="'+(x.id===this.selectedId?'active':'')+'" data-ammo-id="'+this.e(x.id)+'"><strong>'+this.e(x.name)+'</strong><small>'+this.e(x.id)+'</small></button>').join("");list.querySelectorAll("[data-ammo-id]").forEach(b=>b.onclick=()=>{this.selectedId=b.dataset.ammoId;this.render()});this.renderEditor()}
  renderEditor(){const h=this.el.querySelector("[data-ammo-editor]"),a=this.current();if(!a){h.innerHTML='<div class="tq-ships__empty">Crie ou selecione uma munição.</div>';return}h.innerHTML='<section class="tq-ships__panel"><div class="tq-ships__panel-title"><div><strong>Tipo de munição</strong><small>Jogadores precisam possuir unidades. NPCs recebem permissão por perfil.</small></div></div><div class="tq-ships__settings tq-ships__settings--v2"><label><span>Nome</span><input data-a-name value="'+this.e(a.name)+'"></label><label><span>Dano</span><input data-a-damage type="number" min="0" max="10000" value="'+Number(a.damage||0)+'"></label><label><span>Velocidade do projétil</span><input data-a-speed type="number" min="1" max="10000" value="'+Number(a.projectileSpeed||720)+'"></label><label><span>Tamanho</span><input data-a-size type="number" min=".1" max="10" step=".1" value="'+Number(a.size||1)+'"></label><label><span>Cooldown (ms)</span><input data-a-cooldown type="number" min="0" max="60000" value="'+Number(a.cooldownMs||900)+'"></label><label><span>Efeito do projétil</span><input data-a-projectile value="'+this.e(a.effects?.projectile||"standard")+'"></label><label><span>Efeito de impacto</span><input data-a-impact value="'+this.e(a.effects?.impact||"standard")+'"></label><label><span>Splash na água</span><input data-a-splash value="'+this.e(a.effects?.waterSplash||"standard")+'"></label><label><span>Preço na loja</span><input data-a-price type="number" min="0" value="'+Number(a.shop?.price||0)+'"></label><label><span>Disponível</span><input data-a-available type="checkbox" '+(a.available!==false?"checked":"")+'></label><label><span>Vendável na loja</span><input data-a-buy type="checkbox" '+(a.shop?.purchasable!==false?"checked":"")+'></label></div></section>';
    const save=()=>{const v=structuredClone(a);v.name=h.querySelector("[data-a-name]").value;v.damage=Math.max(0,Number(h.querySelector("[data-a-damage]").value)||0);v.projectileSpeed=Math.max(1,Number(h.querySelector("[data-a-speed]").value)||1);v.size=Math.max(.1,Number(h.querySelector("[data-a-size]").value)||1);v.cooldownMs=Math.max(0,Number(h.querySelector("[data-a-cooldown]").value)||0);v.available=h.querySelector("[data-a-available]").checked;v.effects={projectile:h.querySelector("[data-a-projectile]").value,impact:h.querySelector("[data-a-impact]").value,waterSplash:h.querySelector("[data-a-splash]").value};v.shop={purchasable:h.querySelector("[data-a-buy]").checked,price:Math.max(0,Number(h.querySelector("[data-a-price]").value)||0)};this.save(v);this.render()};h.querySelectorAll("input").forEach(x=>x.addEventListener("change",save))
  }
  resolve(id){return this.all().find(x=>x.id===String(id||""))||null}
  e(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
}