export class TreasureEditor{
  constructor({requestAsset}={}){
    this.requestAsset=typeof requestAsset==="function"?requestAsset:null;
    this.catalog={schema:"tq.treasure-catalog",version:1,treasures:[]};
    this.drafts=[];this.selectedId=null;this.storageKey="tq.dev.treasure-drafts:v1";this.el=null;
  }
  async mount(parent){
    this.el=document.createElement("section");this.el.className="tq-dev__ships tq-dev__treasures";this.el.hidden=true;
    this.el.innerHTML='<header><div><strong>Tesouros</strong><small>Coletáveis e recompensas do alto-mar</small></div><button type="button" data-treasure-close aria-label="Fechar">×</button></header><div class="tq-ships__body"><aside class="tq-ships__sidebar"><button type="button" class="tq-ships__new" data-treasure-new>＋ Novo tesouro</button><div class="tq-ships__list" data-treasure-list></div></aside><main class="tq-ships__editor" data-treasure-editor></main></div>';
    parent.append(this.el);this.el.querySelector("[data-treasure-close]").onclick=()=>this.setVisible(false);this.el.querySelector("[data-treasure-new]").onclick=()=>this.createTreasure();await this.load();
  }
  async load(){try{const r=await fetch("./src/config/treasure-catalog.json?v=20261002-1058",{cache:"no-store"});if(r.ok)this.catalog=await r.json()}catch(e){console.warn("Treasure catalog load failed",e)}try{const d=JSON.parse(localStorage.getItem(this.storageKey)||"[]");this.drafts=Array.isArray(d)?d:[]}catch{this.drafts=[]}this.selectedId=this.all()[0]?.id||null;this.render()}
  all(){const m=new Map((this.catalog.treasures||[]).map(x=>[x.id,structuredClone(x)]));for(const x of this.drafts)m.set(x.id,structuredClone(x));return [...m.values()]}
  current(){return this.all().find(x=>x.id===this.selectedId)||null}
  resolve(id){return this.all().find(x=>x.id===String(id||""))||null}
  saveDraft(v){const i=this.drafts.findIndex(x=>x.id===v.id);if(i>=0)this.drafts[i]=v;else this.drafts.push(v);localStorage.setItem(this.storageKey,JSON.stringify(this.drafts));globalThis.dispatchEvent(new CustomEvent("tq:treasureprofilechange",{detail:{treasureId:v.id}}))}
  createTreasure(){let n=1,id="tesouro-"+n;while(this.all().some(x=>x.id===id))id="tesouro-"+(++n);const v={id,name:"Novo tesouro",asset:"",width:88,height:88,rewards:{gold:{min:1,max:10,chance:100},rubies:{min:1,max:1,chance:0}}};this.saveDraft(v);this.selectedId=id;this.render()}
  setVisible(show){if(this.el)this.el.hidden=!show;if(show)this.render()}
  setAsset(id,src){const v=this.resolve(id);if(!v)return false;v.asset=String(src||"");this.saveDraft(v);this.selectedId=id;this.render();return true}
  render(){if(!this.el)return;const list=this.el.querySelector("[data-treasure-list]");list.innerHTML=this.all().map(x=>'<button type="button" class="'+(x.id===this.selectedId?'active':'')+'" data-treasure-id="'+this.e(x.id)+'"><strong>'+this.e(x.name)+'</strong><small>'+this.e(x.id)+'</small></button>').join("");list.querySelectorAll("[data-treasure-id]").forEach(b=>b.onclick=()=>{this.selectedId=b.dataset.treasureId;this.render()});this.renderEditor()}
  renderEditor(){const host=this.el.querySelector("[data-treasure-editor]"),v=this.current();if(!v){host.innerHTML='<div class="tq-ships__empty">Crie ou selecione um tesouro.</div>';return}const g=v.rewards?.gold||{},r=v.rewards?.rubies||{};host.innerHTML='<section class="tq-ships__panel"><div class="tq-ships__panel-title"><div><strong>Tipo de tesouro</strong><small>Asset e sorteios independentes de recompensa.</small></div></div><div class="tq-ships__settings tq-ships__settings--v2"><label><span>Nome</span><input data-t-name value="'+this.e(v.name)+'"></label><label><span>Asset</span><input data-t-asset value="'+this.e(v.asset||"")+'" placeholder="./assets/..."></label><button type="button" data-t-pick>▦ Escolher asset</button><label><span>Largura</span><input data-t-width type="number" min="24" max="512" value="'+Number(v.width||88)+'"></label><label><span>Altura</span><input data-t-height type="number" min="24" max="512" value="'+Number(v.height||88)+'"></label></div></section><section class="tq-ships__panel"><div class="tq-ships__panel-title"><div><strong>🪙 Ouro</strong><small>Quantidade aleatória e chance de conceder.</small></div></div><div class="tq-ships__settings tq-ships__settings--v2">'+this.rewardFields("gold",g)+'</div></section><section class="tq-ships__panel"><div class="tq-ships__panel-title"><div><strong>💎 Rubis</strong><small>Sorteio separado do ouro.</small></div></div><div class="tq-ships__settings tq-ships__settings--v2">'+this.rewardFields("rubies",r)+'</div></section>';
    const save=()=>{const n=structuredClone(v);n.name=host.querySelector("[data-t-name]").value;n.asset=host.querySelector("[data-t-asset]").value;n.width=Math.max(24,Number(host.querySelector("[data-t-width]").value)||88);n.height=Math.max(24,Number(host.querySelector("[data-t-height]").value)||88);n.rewards={gold:this.readReward(host,"gold"),rubies:this.readReward(host,"rubies")};this.saveDraft(n);this.render()};host.querySelectorAll("input").forEach(x=>x.addEventListener("change",save));host.querySelector("[data-t-pick]")?.addEventListener("click",()=>this.requestAsset?.({treasureId:v.id}))}
  rewardFields(k,x){return '<label><span>Mínimo</span><input data-r-min="'+k+'" type="number" min="0" value="'+Math.max(0,Number(x.min)||0)+'"></label><label><span>Máximo</span><input data-r-max="'+k+'" type="number" min="0" value="'+Math.max(0,Number(x.max)||0)+'"></label><label><span>Probabilidade (%)</span><input data-r-chance="'+k+'" type="number" min="0" max="100" step="1" value="'+Math.max(0,Math.min(100,Number(x.chance)||0))+'"></label>'}
  readReward(host,k){const min=Math.max(0,Math.floor(Number(host.querySelector('[data-r-min="'+k+'"]').value)||0));const max=Math.max(min,Math.floor(Number(host.querySelector('[data-r-max="'+k+'"]').value)||min));return{min,max,chance:Math.max(0,Math.min(100,Number(host.querySelector('[data-r-chance="'+k+'"]').value)||0))}}
  e(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
}
